{
  articledetailList {
    items {
      _path
      url
      headline
      subheadline
      shortDescription {
        html
      }
      bannerImage {
        ... on ImageRef {
          _path
        }
      }
      postDate
      content {
        html
      }
    }
  }
}