{
  cardlistconfigList {
    items {
      _path
      headline
      shortDescription {
        html
      }
      searchPath
      enablePostDate
      enableSearch
      cardTags
      filterTags
    }
  }
}