{
	cardList {
    items {
      _path
      headline
      shortDescription {
        html
      }
      callToActions {
        ... on LinkModel {
          linkText
          linkPath
        }
      }
    }
  }
}